const items = [
  {
    id: 1,
    title: "Home Made Pizza",
    category: "pizza",
    imgSrc: "./assets/images/1.jpg",
    rating: 4.5,
    eta: "30–45 min",
    price: "₹249",
    offer: "10% OFF",
  },
  {
    id: 2,
    title: "Cheese Loaded Burger",
    category: "burger",
    imgSrc: "./assets/images/2.jpg",
    rating: 4.4,
    eta: "20–30 min",
    price: "₹199",
    offer: "15% OFF",
  },
  {
    id: 3,
    title: "South Indian Dosa",
    category: "south",
    imgSrc: "./assets/images/3.jpg",
    rating: 4.3,
    eta: "25–35 min",
    price: "₹129",
    offer: "No Offer",
  },
  {
    id: 4,
    title: "Desi Veg Thali",
    category: "combo",
    imgSrc: "./assets/images/4.jpg",
    rating: 4.7,
    eta: "30–40 min",
    price: "₹179",
    offer: "20% OFF",
  },
  {
    id: 5,
    title: "Grilled Sandwich",
    category: "snack",
    imgSrc: "./assets/images/5.jpg",
    rating: 4.2,
    eta: "15–25 min",
    price: "₹139",
    offer: "5% OFF",
  },
  {
    id: 6,
    title: "Chocolate Lava Cake",
    category: "dessert",
    imgSrc: "./assets/images/6.jpg",
    rating: 4.8,
    eta: "10–20 min",
    price: "₹119",
    offer: "No Offer",
  },
  {
    id: 7,
    title: "Masala Fries",
    category: "snack",
    imgSrc: "./assets/images/7.jpg",
    rating: 4.1,
    eta: "15–20 min",
    price: "₹169",
    offer: "10% OFF",
  },
  {
    id: 8,
    title: "Paneer Tikka Platter",
    category: "tandoori",
    imgSrc: "./assets/images/8.jpg",
    rating: 4.6,
    eta: "25–30 min",
    price: "₹209",
    offer: "No Offer",
  },
  {
    id: 9,
    title: "Sweet Gulab Jamun",
    category: "dessert",
    imgSrc: "./assets/images/9.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹180",
    offer: "5% OFF",
  },
  {
    id: 10,
    title: "Sweet Gulab Jamun",
    category: "dessert",
    imgSrc: "./assets/images/8.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹1300",
    offer: "5% OFF",
  },
  {
    id: 11,
    title: "Sweet Gulab Jamun",
    category: "dessert",
    imgSrc: "./assets/images/3.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹150",
    offer: "5% OFF",
  },
  {
    id: 12,
    title: "Sweet Gulab Jamun",
    category: "dessert",
    imgSrc: "./assets/images/7.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹118",
    offer: "5% OFF",
  },
  {
    id: 13,
    title: "Pizza ",
    category: "dessert",
    imgSrc: "./assets/images/13.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹118",
    offer: "5% OFF",
  },
  {
    id: 14,
    title: "Paneer Pizza",
    category: "Indian",
    imgSrc: "./assets/images/14.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹228",
    offer: "5% OFF",
  },
  {
    id: 15,
    title: "Creem Pizza",
    category: "dessert",
    imgSrc: "./assets/images/15.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹218",
    offer: "5% OFF",
  },
  {
    id: 16,
    title: "Paneer Tikka Platter",
    category: "tandoori",
    imgSrc: "./assets/images/8.jpg",
    rating: 4.6,
    eta: "25–30 min",
    price: "₹209",
    offer: "No Offer",
  },
];
