const popularItems = [
  {
    title: "Cheese Burst Pizza",
    imgSrc: "./assets/images/p1.jpg",
    rating: 4.5,
    eta: "10–15 min",
    price: "₹249",
    offer: "10% OFF",
  },
  {
    title: "Loaded Fries",
    imgSrc: "./assets/images/p2.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹149",
    offer: "7% OFF",
  },
  {
    title: "Sizzling Brownie",
    imgSrc: "./assets/images/p3.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹199",
    offer: "5% OFF",
  },
  {
    title: "Veg fry Rice",
    imgSrc: "./assets/images/p4.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹199",
    offer: "5% OFF",
  },
  {
    title: "Burger",
    imgSrc: "./assets/images/p5.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹199",
    offer: "8% OFF",
  },
  {
    title: "Veg Pulao",
    imgSrc: "./assets/images/p6.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹199",
    offer: "9% OFF",
  },
  {
    title: "Paneer Pulao",
    imgSrc: "./assets/images/p7.jpg",
    rating: 4.9,
    eta: "10–15 min",
    price: "₹249",
    offer: "5% OFF",
  },
];
